# Configuration Spring Boot pour abonnement-service
server.port=8085

# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5400/glop
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Nom de l'application
spring.application.name=abonnement-service

# Error details (debug)
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-binding-errors=always

# Logging
logging.level.com.ciblorgasport=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG
