server:
  port: 8084

spring:
  datasource:
    url: ${INC_DB_URL:jdbc:postgresql://localhost:5432/ciblorgasport_incident}
    username: ${INC_DB_USER:postgres}
    password: ${INC_DB_PASS:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 30000
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      keepalive-time: 300000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO