spring.application.name=resultats-service

# Server
server.port=8088

# Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5400/glop
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# HikariCP
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# JWT
ciblorgasport.app.jwtSecret=mySuperSecretKeyForCiblorgasportApplicationThatIsVeryLongAndSecure
ciblorgasport.app.jwtExpirationMs=86400000

# Services
event-service.url=http://localhost:8084
participants-service.url=http://localhost:8087

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
